default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  pool: 5

development:
  <<: *default
  database: myapp_development

production:
  <<: *default
  database: myapp_production

test:
  <<: *default
  database: myapp_test